//
//  Hard.swift
//  PazleBox
//
//  Created by jun on 2019/03/09.
//  Copyright © 2019 jun. All rights reserved.
//

import Foundation


class Hard {
   
   var HStage: Array<Any> = Array()
   
   var H1: [[Contents]] = Array()
   var H2: [[Contents]] = Array()
   var H3: [[Contents]] = Array()
   var H4: [[Contents]] = Array()
   var H5: [[Contents]] = Array()
   var H6: [[Contents]] = Array()
   var H7: [[Contents]] = Array()
   var H8: [[Contents]] = Array()
   var H9: [[Contents]] = Array()
   var H10: [[Contents]] = Array()
   var H11: [[Contents]] = Array()
   var H12: [[Contents]] = Array()
   var H13: [[Contents]] = Array()
   var H14: [[Contents]] = Array()
   var H15: [[Contents]] = Array()
   var H16: [[Contents]] = Array()
   var H17: [[Contents]] = Array()
   var H18: [[Contents]] = Array()
   var H19: [[Contents]] = Array()
   var H20: [[Contents]] = Array()
   var H21: [[Contents]] = Array()
   var H22: [[Contents]] = Array()
   var H23: [[Contents]] = Array()
   var H24: [[Contents]] = Array()
   var H25: [[Contents]] = Array()
   var H26: [[Contents]] = Array()
   var H27: [[Contents]] = Array()
   var H28: [[Contents]] = Array()
   var H29: [[Contents]] = Array()
   var H30: [[Contents]] = Array()
   var H31: [[Contents]] = Array()
   var H32: [[Contents]] = Array()
   var H33: [[Contents]] = Array()
   var H34: [[Contents]] = Array()
   var H35: [[Contents]] = Array()
   var H36: [[Contents]] = Array()
   var H37: [[Contents]] = Array()
   var H38: [[Contents]] = Array()
   var H39: [[Contents]] = Array()
   var H40: [[Contents]] = Array()
   var H41: [[Contents]] = Array()
   var H42: [[Contents]] = Array()
   var H43: [[Contents]] = Array()
   var H44: [[Contents]] = Array()
   var H45: [[Contents]] = Array()
   var H46: [[Contents]] = Array()
   var H47: [[Contents]] = Array()
   var H48: [[Contents]] = Array()
   var H49: [[Contents]] = Array()
   var H50: [[Contents]] = Array()

   
   init() {
      
   
      InitH1()
      InitH2()
      InitH3()
      InitH4()
      InitH5()
      InitH6()
      InitH7()
      InitH8()
      InitH9()
      InitH10()
      InitH11()
      InitH12()
      InitH13()
      InitH14()
      InitH15()
      InitH16()
      InitH17()
      InitH18()
      InitH19()
      InitH20()
      InitH21()
      InitH22()
      InitH23()
      InitH24()
      InitH25()
      InitH26()
      InitH27()
      InitH28()
      InitH29()
      InitH30()
      InitH31()
      InitH32()
      InitH33()
      InitH34()
      InitH35()
      InitH36()
      InitH37()
      InitH38()
      InitH39()
      InitH40()
      InitH41()
      InitH42()
      InitH43()
      InitH44()
      InitH45()
      InitH46()
      InitH47()
      InitH48()
      InitH49()
      InitH50()
      
      InitGetAllHardStage()
   }
   
   private func InitGetAllHardStage(){
      
      HStage = self.getHardStage()
   }
   
   private func getHardStage() ->Array<Any>  {
      
      var ReturnStage: Array<Any> = Array()
      
      ReturnStage.append(contentsOf: H1)
      ReturnStage.append(contentsOf: H2)
      ReturnStage.append(contentsOf: H3)
      ReturnStage.append(contentsOf: H4)
      ReturnStage.append(contentsOf: H5)
      ReturnStage.append(contentsOf: H6)
      ReturnStage.append(contentsOf: H7)
      ReturnStage.append(contentsOf: H8)
      ReturnStage.append(contentsOf: H9)
      ReturnStage.append(contentsOf: H10)
      ReturnStage.append(contentsOf: H11)
      ReturnStage.append(contentsOf: H12)
      ReturnStage.append(contentsOf: H13)
      ReturnStage.append(contentsOf: H14)
      ReturnStage.append(contentsOf: H15)
      ReturnStage.append(contentsOf: H16)
      ReturnStage.append(contentsOf: H17)
      ReturnStage.append(contentsOf: H18)
      ReturnStage.append(contentsOf: H19)
      ReturnStage.append(contentsOf: H20)
      ReturnStage.append(contentsOf: H21)
      ReturnStage.append(contentsOf: H22)
      ReturnStage.append(contentsOf: H23)
      ReturnStage.append(contentsOf: H24)
      ReturnStage.append(contentsOf: H25)
      ReturnStage.append(contentsOf: H26)
      ReturnStage.append(contentsOf: H27)
      ReturnStage.append(contentsOf: H28)
      ReturnStage.append(contentsOf: H29)
      ReturnStage.append(contentsOf: H30)
      ReturnStage.append(contentsOf: H31)
      ReturnStage.append(contentsOf: H32)
      ReturnStage.append(contentsOf: H33)
      ReturnStage.append(contentsOf: H34)
      ReturnStage.append(contentsOf: H35)
      ReturnStage.append(contentsOf: H36)
      ReturnStage.append(contentsOf: H37)
      ReturnStage.append(contentsOf: H38)
      ReturnStage.append(contentsOf: H39)
      ReturnStage.append(contentsOf: H40)
      ReturnStage.append(contentsOf: H41)
      ReturnStage.append(contentsOf: H42)
      ReturnStage.append(contentsOf: H43)
      ReturnStage.append(contentsOf: H44)
      ReturnStage.append(contentsOf: H45)
      ReturnStage.append(contentsOf: H46)
      ReturnStage.append(contentsOf: H47)
      ReturnStage.append(contentsOf: H48)
      ReturnStage.append(contentsOf: H49)
      ReturnStage.append(contentsOf: H50)
      
      return ReturnStage
   }
}
