//
//  Normal.swift
//  PazleBox
//
//  Created by jun on 2019/03/09.
//  Copyright © 2019 jun. All rights reserved.
//

import Foundation


class Normal {
   
   var NStage: Array<Any> = Array()
   
   var N1: [[Contents]] = Array()
   var N2: [[Contents]] = Array()
   var N3: [[Contents]] = Array()
   var N4: [[Contents]] = Array()
   var N5: [[Contents]] = Array()
   var N6: [[Contents]] = Array()
   var N7: [[Contents]] = Array()
   var N8: [[Contents]] = Array()
   var N9: [[Contents]] = Array()
   var N10: [[Contents]] = Array()
   var N11: [[Contents]] = Array()
   var N12: [[Contents]] = Array()
   var N13: [[Contents]] = Array()
   var N14: [[Contents]] = Array()
   var N15: [[Contents]] = Array()
   var N16: [[Contents]] = Array()
   var N17: [[Contents]] = Array()
   var N18: [[Contents]] = Array()
   var N19: [[Contents]] = Array()
   var N20: [[Contents]] = Array()
   var N21: [[Contents]] = Array()
   var N22: [[Contents]] = Array()
   var N23: [[Contents]] = Array()
   var N24: [[Contents]] = Array()
   var N25: [[Contents]] = Array()
   var N26: [[Contents]] = Array()
   var N27: [[Contents]] = Array()
   var N28: [[Contents]] = Array()
   var N29: [[Contents]] = Array()
   var N30: [[Contents]] = Array()
   var N31: [[Contents]] = Array()
   var N32: [[Contents]] = Array()
   var N33: [[Contents]] = Array()
   var N34: [[Contents]] = Array()
   var N35: [[Contents]] = Array()
   var N36: [[Contents]] = Array()
   var N37: [[Contents]] = Array()
   var N38: [[Contents]] = Array()
   var N39: [[Contents]] = Array()
   var N40: [[Contents]] = Array()
   var N41: [[Contents]] = Array()
   var N42: [[Contents]] = Array()
   var N43: [[Contents]] = Array()
   var N44: [[Contents]] = Array()
   var N45: [[Contents]] = Array()
   var N46: [[Contents]] = Array()
   var N47: [[Contents]] = Array()
   var N48: [[Contents]] = Array()
   var N49: [[Contents]] = Array()
   var N50: [[Contents]] = Array()
   
   init() {
     
      
      InitN1()
      InitN2()
      InitN3()
      InitN4()
      InitN5()
      InitN6()
      InitN7()
      InitN8()
      InitN9()
      InitN10()
      InitN11()
      InitN12()
      InitN13()
      InitN14()
      InitN15()
      InitN16()
      InitN17()
      InitN18()
      InitN19()
      InitN20()
      InitN21()
      InitN22()
      InitN23()
      InitN24()
      InitN25()
      InitN26()
      InitN27()
      InitN28()
      InitN29()
      InitN30()
      InitN31()
      InitN32()
      InitN33()
      InitN34()
      InitN35()
      InitN36()
      InitN37()
      InitN38()
      InitN39()
      InitN40()
      InitN41()
      InitN42()
      InitN43()
      InitN44()
      InitN45()
      InitN46()
      InitN47()
      InitN48()
      InitN49()
      InitN50()
      
      InitGetAllEasyStage()
   }
   
   private func InitGetAllEasyStage(){
      
      NStage = self.getNormalStage()
   }
   
   private func getNormalStage() ->Array<Any>  {
      
      var ReturnStage: Array<Any> = Array()
      
      ReturnStage.append(contentsOf: N1)
      ReturnStage.append(contentsOf: N2)
      ReturnStage.append(contentsOf: N3)
      ReturnStage.append(contentsOf: N4)
      ReturnStage.append(contentsOf: N5)
      ReturnStage.append(contentsOf: N6)
      ReturnStage.append(contentsOf: N7)
      ReturnStage.append(contentsOf: N8)
      ReturnStage.append(contentsOf: N9)
      ReturnStage.append(contentsOf: N10)
      ReturnStage.append(contentsOf: N11)
      ReturnStage.append(contentsOf: N12)
      ReturnStage.append(contentsOf: N13)
      ReturnStage.append(contentsOf: N14)
      ReturnStage.append(contentsOf: N15)
      ReturnStage.append(contentsOf: N16)
      ReturnStage.append(contentsOf: N17)
      ReturnStage.append(contentsOf: N18)
      ReturnStage.append(contentsOf: N19)
      ReturnStage.append(contentsOf: N20)
      ReturnStage.append(contentsOf: N21)
      ReturnStage.append(contentsOf: N22)
      ReturnStage.append(contentsOf: N23)
      ReturnStage.append(contentsOf: N24)
      ReturnStage.append(contentsOf: N25)
      ReturnStage.append(contentsOf: N26)
      ReturnStage.append(contentsOf: N27)
      ReturnStage.append(contentsOf: N28)
      ReturnStage.append(contentsOf: N29)
      ReturnStage.append(contentsOf: N30)
      ReturnStage.append(contentsOf: N31)
      ReturnStage.append(contentsOf: N32)
      ReturnStage.append(contentsOf: N33)
      ReturnStage.append(contentsOf: N34)
      ReturnStage.append(contentsOf: N35)
      ReturnStage.append(contentsOf: N36)
      ReturnStage.append(contentsOf: N37)
      ReturnStage.append(contentsOf: N38)
      ReturnStage.append(contentsOf: N39)
      ReturnStage.append(contentsOf: N40)
      ReturnStage.append(contentsOf: N41)
      ReturnStage.append(contentsOf: N42)
      ReturnStage.append(contentsOf: N43)
      ReturnStage.append(contentsOf: N44)
      ReturnStage.append(contentsOf: N45)
      ReturnStage.append(contentsOf: N46)
      ReturnStage.append(contentsOf: N47)
      ReturnStage.append(contentsOf: N48)
      ReturnStage.append(contentsOf: N49)
      ReturnStage.append(contentsOf: N50)
      
      return ReturnStage
   }
}
